config/routes.rb
WwWineriesWeb::Application.routes.draw do
  root "wineries#index"
  get '/wineries'  => "wineries#index"
  resources :wineries
end

app/models/winery.rb
require 'csv'

class Winery < ActiveRecord::Base
  has_attached_file :logo, :styles => { :pin => "35x35" }
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.import(file_path)
    CSV.foreach(file_path, headers: true) do |row|
      Winery.create! row.to_hash
    end
  end

  def as_json(*args)
    super.tap do |hash|
      hash["value"] = hash.delete "name"
      hash.delete "created_at"
      hash.delete "updated_at"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController

  def index
    respond_to do |format|
      format.json do
        @wineries = Winery.all.as_json
        render json: @wineries
      end
      format.html do
        @wineries = Winery.all
      end
    end
  end

  def new
    @winery = Winery.new
  end

  def edit
    @winery = Winery.find(params[:id])
  end

  def create
    @winery = Winery.create(winery_params)
    if @winery.save
    end
  end

  def update
    @winery = Winery.find(params[:id])
    if @winery.update(winery_params)
      redirect_to root_path
    end
  end

  def destroy
    @winery = Winery.find(params[:id])
    if @winery.destroy
    end
  end

  private

  def winery_params
    params.require(:winery).permit(:logo, :name, :address, :city, :state, :zip, :latitude, :longitude, :phone, :website, :twitter, :facebook)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walla Walla Wineries</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/wineries/_form.html.erb
<div class="winery-form">
<%= form_for(@winery) do |f| %>
  <%= f.label "Logo:" %>
  <%= f.file_field :logo %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %>
  <%= f.label "Address:" %>
  <%= f.text_field :address %>
  <%= f.label "City:" %>
  <%= f.text_field :city %>
  <%= f.label "State:" %>
  <%= f.text_field :state %>
  <%= f.label "Zip:" %>
  <%= f.text_field :zip %>
  <%= f.label "Latitude:" %>
  <%= f.text_field :latitude %>
  <%= f.label "Longitude:" %>
  <%= f.text_field :longitude %>
  <%= f.label "Phone Number:" %>
  <%= f.text_field :phone %>
  <%= f.label "Website:" %>
  <%= f.text_field :website %>
  <%= f.label "Twitter:" %>
  <%= f.text_field :twitter %>
  <%= f.label "Facebook:" %>
  <%= f.text_field :facebook %><br>
  <%= f.submit "Submit", class: "button" %>
<% end %>
</div>

app/views/wineries/edit.html.erb
<h1 class="winery-form-header">
  Editing Winery
</h1>
<%= render 'form' %>

app/views/wineries/index.html.erb
<h1>Wineries</h1>

<table class="table-borders">
  <thead>
    <tr>
      <th>Winery</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @wineries.each do |winery| %>
      <tr>
        <td><%= link_to winery.name, edit_winery_path(winery) %></td>
        <td><%= winery.address %></td>
        <td><%= winery.city %></td>
        <td><%= winery.state %></td>
        <td><%= winery.zip %></td>
        <td><%= winery.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wineries/new.html.erb
<%= render 'form' %>